### ISSUE TITLE
include_children parameter does not work

### ISSUE THREAD

**Issue by newgene** [biothings/biothings.species#3]
For this query:

http://t.biothings.io/v1/taxon/1280?include_children=1

when `include_children=1` is passed, the `children` field should return a list of children nodes of the current taxonomy node. Currently it's returned as an empty list.

The expected children nodes are like this list:

https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=1280

**Comment by zcqian** [comment]
fixed via https://github.com/biothings/biothings.species/commit/f1a768de83aad416154713e89ee32460f431992e
